### PR TITLE
Feature/user page

### PR DESCRIPTION
**Pull request by ritualz**
Updated user page, tests. 

Added more fields into the usermodel, (cover-image, about and gender).
Also moved FriendRequest to the dashboard

### CODE REVIEW

**Comment by runarf** [comment]
The new user page looks real good. But when I try to access a public trip from the explore view I am denied from accessing it? How are you suppose to enter a public trip page?

**Comment by ritualz** [comment]
Do you mean using the button on the dashboard (http://localhost:3000/trips)? I not think we will use that one, take a look at the explore map (http://localhost:3000/explore).

**Comment by runarf** [comment]
yea I tried using the explore view. When i try to click the trip I get "You are not authorized to perform this action"

**Comment by ritualz** [comment]
Strange, i not get the error. 
> Create a trip, set as public
> Login with another user
> Go to explore, click on trip
> End up at the public view.

**Comment by runarf** [comment]
Ah my mistake. Forgot to make the trip public :/

**Comment by ritualz** [comment]
I see :) There might be some bugs in the code, and im seeing some translations missing too. But we can do that after the workshop tomorrow.

**Pull request merged**
