### PR TITLE
CRUD implemented 

### PR DESCRIPTION
**Pull request by ritualz**

### CODE REVIEW

**Comment by sewelol** [comment]
yes

**Comment by fsauter** [comment]
Give us some more hours to do the review next time :D

And we may add the Story ID to the commit for the feature? Like #S3: Implemented create trip functionality..

**Comment by ritualz** [comment]
I'll remember that for the next time :) 
It seems like heroku isn't updating too.

**Comment by fsauter** [comment]
True, I'm going to look into this at the weekend or maybe tomorrow!

**Pull request merged**
