### PR TITLE
Continued working on map

### PR DESCRIPTION
**Pull request by sewelol**
There is no link to the map, but is found at  e.g. localhost:3000/trips/1/map

When clicking the map, a waypoint will be created, and a line is drawn from the last waypoint to the new.

TODO: 
- Save the waypoints in a JSON format, which could then be passed to and from the database.
- Integrate the map view into the Trip tabs

### CODE REVIEW

**Comment by fsauter** [comment]
Before we merge we may should have a look at the commits together, we can may rebase some changes :)

**Comment by sewelol** [comment]
That's okay, I guess?

Sorry chief, I thought I'd just add a suggestions for the logo, so that everyone could check it out ;)

**Comment by fsauter** [comment]
That's totally okay! I just meant that it would be possible to bundle all the "merge" commits into one for a cleaner history.. but if you want to keep it like this, go for it

We should also talk about feature branches so we can separate merge requests :)

Chief over and out

**Comment by sewelol** [comment]
Started a new branch for these features.

**Pull request closed without merging**
